version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: pzfreo/clo-nodejs
    depends_on: 
      - db
    ports: 
      - "80:8080"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "db:3306", "--","npm", "run","server"]
    networks:
      - backend
    environment: 
      DEBUG: "*:*"
      DBUSER: "root"
      DBPW: "secret"
      DBHOST: "db"
      DBNAME: "oxclo"
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: pzfreo/clo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "oxclo"
      MYSQL_ROOT_PASSWORD: "secret"
    networks: 
      - backend
networks:
  backend:
    driver: bridge  